# Generated by Django 6.1.1 on 2026-09-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('u', 'upcoming'), ('o', 'Overdue'), ('r', 'returned')], default='u', max_length=1),
        ),
    ]
