# Generated by Django 6.1.1 on 2026-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('u', 'upcoming'), ('o', 'Overdue'), ('r', 'returned')], max_length=1),
        ),
    ]
