# Generated by Django 6.1.1 on 2026-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='send_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
