# Generated by Django 6.1.1 on 2026-09-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_remove_reminder_send_at_reminder_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remined_at',
        ),
    ]
