# Generated by Django 6.1.1 on 2026-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_reminder_is_read_remove_reminder_remined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('b', 'borrowed'), ('u', 'upcoming'), ('o', 'Overdue'), ('r', 'returned')], max_length=1),
        ),
    ]
