# Generated by Django 6.1.1 on 2026-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_reminder_is_read_reminder_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-created_at']},
        ),
    ]
