# Generated by Django 6.1.1 on 2026-09-24 22:23

import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=loans.models.calculate_due_date),
        ),
    ]
