# Generated by Django 6.1.1 on 2026-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_created_at_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrowed_at']},
        ),
    ]
